### ISSUE TITLE
Feature Request: Allow setting the width, height and font-size of the quick-popup.

### ISSUE THREAD

**Issue by raphaeldore** [tranxuanthang/quick-dictionary-2#1]
Hi,

First: Congratulation on the 2.0 release!

I've been using quick-dictionary for a while, and I like it quite a bit, but I noticed that on my 4k display the quick-popup is a little small, as is the font (0.725rem is a bit small, 1em would be perfect for me). Here is a picture showing how it looks on my side:

![](https://i.imgur.com/apqRaKH.jpg "Example")

As you can see, it's not unusable, bit it's a bit small.

I'm not sure if you take feature requests (sorry if you don't), but I'd like to be able to set the width, height and font-size in the options.

Have a nice day,
Raphaël

**Comment by tranxuanthang** [comment]
Hi @raphaeldore. Thanks for posting the issue. I'm glad users are starting to notice my first big update for this project.

I had been focusing on improving core features in this 2.0.0 update, so there are only few customization options for now. More options will definitely coming soon, including popup's size and font-size, or even custom css, if there are people need it.

Feel free to give any request/suggestion and I'll try to do it whenever I have free time.

**Comment by tranxuanthang** [comment]
I've made some options to control how Quick Dictionary looks on HiDPI devices, and will release a new version soon. If anything is wrong then please tell me.

Example:
![appearancescale](https://user-images.githubusercontent.com/15942946/37237752-c334a17c-244a-11e8-87e9-2e68bf763d4d.png)
![newcustomizations](https://user-images.githubusercontent.com/15942946/37237753-c3691b46-244a-11e8-8f33-27a033a0a703.png)

**Comment by raphaeldore** [comment]
Looks good to me. Thanks for looking into this!

**Comment by tranxuanthang** [comment]
Version 2.0.1 is live now so check it out if you haven't.
